### ISSUE TITLE
Cmake build wrong CUDA architecture

### ISSUE THREAD

**Issue by lehuyduc** [ZhenshengLee/cuosqp#1]
Hello,

In `cuosqp/CMakeLists.txt`, I've added the following lines:
```
set(CMAKE_CUDA_ARCHITECTURES 75)
set(CUDA_ARCHITECTURES 75)
```

However, when I `cmake --build .`, it runs into `error: no instance of overloaded function "atomicAdd" matches the argument list argument types are: (double *, double)`.

This is because the compiler keeps setting `arch=compute52_52,code=sm_52` (I found this by running `grep -rn . -e "sm_"` in `cuosqp/build` folder). I have no idea where the number 52 comes from, because it runs fine on Google Colab but not on my PC.

So, what's the correct way to set `CUDA_ARCHITECTURES` ? My machine has cuda-11.4 and 2080ti

Thanks!

**Comment by ZhenshengLee** [comment]
refer to this https://developer.nvidia.com/cuda-gpus

**Comment by lehuyduc** [comment]
Okay I found the solution. It should use
`set(CUDA_NVCC_FLAGS ${CUDA_NVCC_FLAGS}; "-gencode arch=compute_75,code=sm_75")`
instead of
`set(CMAKE_CUDA_FLAGS "-gencode ach=compute_70,code=sm_75")`

Thanks!
